on: workflow_dispatch
jobs:
  run-python-script: 
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4
      
    - name: Set up python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install package
      run: pip install openpyxl
      
    - name: Run Python script
      run: python data/db_updater.py
