on: workflow_dispatch
jobs:
  run-python-script: 
    runs-on: ubuntu-latest

    steps:
    - name: Set up python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Run Python script
      run: python 375-AgQuery/data/db_updater.py
